on:
  push:
  workflow_dispatch:
    inputs:
      BUILD_NUMBER:
        description: build number
        required: false
        default: ''
      DOCKER_CHANNEL:
        description: edge or stable
        required: true
        default: edge

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          go get github.com/aktau/github-release
          go env
          github-release --help
          if [ -n "$BUILD_NUMBER" ];then BUILD_NUMBER="${BUILD_NUMBER}/"
          curl https://download.docker.com/win/${DOCKER_CHANNEL:-edge}/${BUILD_NUMBER}Docker%20Desktop%20Installer.exe -o Docker.exe
          curl https://download.docker.com/mac/${DOCKER_CHANNEL:-edge}/${BUILD_NUMBER}Docker.dmg -O
          github-release upload --user khs1994-docker --repo docker-desktop-mirror --tag ${DOCKER_CHANNEL:-edge} --name "Docker.exe" --file "Docker.exe" -R
          github-release upload --user khs1994-docker --repo docker-desktop-mirror --tag ${DOCKER_CHANNEL:-edge} --name "Docker.dmg" --file "Docker.dmg" -R
        env:
          GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}
          BUILD_NUMBER=${{github.event.inputs.BUILD_NUMBER}}
          DOCKER_CHANNEL=${{github.event.inputs.DOCKER_CHANNEL}}
